#service:
#  # Идентификатор сервиса
#  id: prediction-service
#  # Описание сервиса
#  title: Сервис предсказания успеваемости
spring:
  datasource:
    # URL-адрес базы данных PostgreSQL
    url:
    # Имя пользователя базы данных
    username:
    # Пароль пользователя базы данных
    password:
    hikari:
      # Максимальное количество подключений к базе данных в пуле
      maximum-pool-size: 10
      # Минимальное количество простаивающих подключений к базе данных в пуле
      minimum-idle: 5
      # Максимальное количество миллисекунд, в течение которых клиент будет ждать подключение из пула
      connection-timeout: 3000
      # Максимальное количество миллисекунд, в течение которых соединение с базой данных разрешено простаивать в пуле
      idle-timeout: 60000
      # Максимальное количество миллисекунд, в течение которых пул будет ждать подтверждения соединения как живого
      validation-timeout: 500