
# Настройки springdoc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: swagger-ui.html
# Команда для сохранения доки: curl -o openapi.yaml http://localhost:8080/v3/api-docs.yaml

spring:
  security:
    user:
      name: user
      password: 123456

  datasource:
    # URL-адрес базы данных PostgreSQL
    url: 'jdbc:postgresql://localhost:5432/prediction_service'
    # Имя пользователя базы данных
    username: 'prediction_service'
    # Пароль пользователя базы данных
    password: 'prediction_service'
    hikari:
      # Максимальное количество подключений к базе данных в пуле
      maximum-pool-size: 10
      # Минимальное количество простаивающих подключений к базе данных в пуле
      minimum-idle: 5
      # Максимальное количество миллисекунд, в течение которых клиент будет ждать подключение из пула
      connection-timeout: 3000
      # Максимальное количество миллисекунд, в течение которых соединение с базой данных разрешено простаивать в пуле
      idle-timeout: 60000
      # Максимальное количество миллисекунд, в течение которых пул будет ждать подтверждения соединения как живого
      validation-timeout: 500